<?php

namespace Bidweb\BidwebBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ApplicationJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationJobRepository extends EntityRepository {

    public function getApplicationJobByStatus($status, $id_job, $limit = null) {
        $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->where('b.status = :st')
                ->andWhere('b.job = :jobid')
                ->addOrderBy('b.created', 'DESC')
                ->setParameter('jobid', $id_job)
                ->setParameter('st', $status);

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                        ->getResult();
    }

    public function getWorker($id_user, $status, $limit = null) {
        $qb = $this->createQueryBuilder('b')
                ->select('b, j')
                ->join('b.job', 'j', Join::WITH, 'j.user = :user_id')
                ->where('b.status = :st')
                ->setParameter('user_id', $id_user)
                ->setParameter('st', $status);
        //echo $qb->getQuery()->getSQL();die;
        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                        ->getResult();
    }

}
