<?php

namespace Bidweb\BidwebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    public function getCityByState($state){
        
       $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.state = :state_id')
                   ->addOrderBy('c.name')
                   ->setParameter('state_id', $state);

        return $qb->getQuery()
                  ->getResult();
    }

}
