<?php

namespace Bidweb\BidwebBundle\Repository;

/**
 * DatabaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatabaseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestDatabase($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
                   ->select('b')
                   ->addOrderBy('b.created', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
    
    public function searchDatabase($text,$limit=null)
    {
        $qb = $this->createQueryBuilder('b')
                   ->select('b')
                   ->where('b.title LIKE :text')
                   ->orWhere('b.detail LIKE :text')
                   ->addOrderBy('b.created', 'DESC')
                ->setParameter('text', "%$text%");

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
}
