<?php

namespace Bidweb\BidwebBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getNotifications($id,$limit=null){
        $qb = $this->createQueryBuilder('n')
                   ->select('n')
                   ->where('n.user = :id')
                   ->addOrderBy('n.created', 'DESC')
                ->setParameter('id', $id);

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
    
    public function getNotifAccount($id){
        $qb = $this->createQueryBuilder('b')
                   ->select('count(b.id)')
                   ->where('b.user = :id')
                   ->andWhere("b.read = false")
                   ->setParameter('id', $id);

     
        return $qb->getQuery()
                  ->getSingleScalarResult();
    }
}
