<?php

namespace Bidweb\BidwebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getLatestPost($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
                   ->select('b, c')
                   ->leftJoin('b.comments', 'c')
                   ->addOrderBy('b.created', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }

    public function searchPost($text,$limit=null)
    {
        $qb = $this->createQueryBuilder('b')
                   ->select('b')
                   ->where('b.title LIKE :text')
                   ->orWhere('b.description LIKE :text')
                   ->addOrderBy('b.created', 'DESC')
                ->setParameter('text', "%$text%");

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
}
