services:
#    user.example:
#        class: Bidweb\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#    bidweb_user.form.type:
#            class: Bidweb\UserBundle\Form\Type\RegistrationFormType
#            tags:
#                - { name: form.type, alias: bidweb_user_registration }
#    bidweb_user.edit.form.type:
#            class: Bidweb\UserBundle\Form\Type\ProfileFormType
#            tags:
#                - { name: form.type, alias: bidweb_user_profile }